version: "3.9"

services:

  mongodb:
    image: mongo:7
    command: ["--quiet"]
    container_name: careslot-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    container_name: careslot-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis

  server1:
    build: ./server
    container_name: careslot-server-1
    restart: always
    depends_on:
      - mongodb
      - redis
    env_file:
      - ./server/.env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/careslot

  server2:
    build: ./server
    container_name: careslot-server-2
    restart: always
    depends_on:
      - mongodb
      - redis
    env_file:
      - ./server/.env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/careslot

  server3:
    build: ./server
    container_name: careslot-server-3
    restart: always
    depends_on:
      - mongodb
      - redis
    env_file:
      - ./server/.env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/careslot

  nginx:
    build: ./client
    container_name: careslot-nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - server1
      - server2
      - server3

volumes:
  mongo-data:
  redis-data: