# version: "3.9"

# services:

#   server:
#     build: ./server
#     container_name: careslot-server
#     ports:
#       - "5000:5000"
#     env_file:
#       - ./server/.env

#   client:
#     build: ./client
#     container_name: careslot-client
#     ports:
#       - "5173:5173"
#     depends_on:
#       - server



version: "3.9"

services:

  server:
    build: ./server
    container_name: careslot-server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env

  nginx:
    build: ./client
    container_name: careslot-nginx
    ports:
      - "80:80"
    depends_on:
      - server